### ISSUE TITLE
Ryan Review: {MVP: User Auth}

### ISSUE THREAD

**Issue by juliawang105** [juliawang105/fullstack#2]
- [x] Backend: DB, model, controller, views
- [x] Redux Loop: ajax, actions, reducer
- [x] Presentational Components and Containers
- [x] Styling
- [x] Smooth, bug-free navigation
- [x] Adequate and appropriate seeds

https://brainscape-learnit.herokuapp.com/#/

**Comment by ryan-mapa** [comment]
Clean.
